# Generated by Django 5.2.8 on 2025-12-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='image_new/images'),
        ),
    ]
